import { App } from 'vue';
import '@/css/var.less';
/***** 按需导出 *****/
export * from './directives/anchor';
export * from './directives/drag';
export * from './directives/observe';
export * from './directives/prop';
export * from './directives/px';
export * from './directives/resize';
export * from './directives/ripple';
export * from './directives/scroll';
export * from './directives/spy';
export * from './directives/upload';
export * from './components/icon';
export * from './components/badge';
export * from './components/button';
export * from './components/triangle';
export * from './components/layer';
export * from './components/label';
export * from './components/input';
export * from './components/loading';
export * from './components/loading-bar';
export * from './components/msgbox';
export * from './components/divider';
export * from './components/cell';
export * from './components/cell-group';
export * from './components/checkbox';
export * from './components/radio';
export * from './components/sign';
export * from './components/roll';
export * from './components/row';
export * from './components/col';
export * from './components/autocomplete';
export * from './components/overlay';
export * from './components/popup';
export * from './components/dropdown';
export * from './components/tooltip';
export * from './components/transition-slide';
export * from './components/switch';
export * from './components/navbar';
export * from './components/notify';
export * from './components/actionsheet';
export * from './components/calendar';
export * from './components/circle-progress';
export * from './components/collapse';
export * from './components/collapse-item';
export * from './components/date-chooser';
export * from './components/date-native-picker';
export * from './components/picker';
export * from './components/progress';
export * from './components/slider';
export * from './components/date-picker';
export * from './components/field';
export * from './components/form';
export * from './components/form-el';
export * from './components/image';
export * from './components/color-picker';
export * from './components/list';
export * from './components/modal';
export * from './components/page';
export * from './components/search';
export * from './components/select';
export * from './components/skeleton';
export * from './components/steps';
export * from './components/step';
export * from './components/stepper';
export * from './components/number-keyboard';
export * from './components/toast';
export * from './components/pull-refresh';
export * from './components/dialog';
export * from './components/swipe-cell';
export * from './components/tabbar';
export * from './components/table';
export * from './components/tabs';
export * from './components/tab';
export * from './components/carousel';
export * from './components/carousel-item';
export * from './components/rich-image';
export * from './components/image-preview';
export type * from './directives/anchor';
export type * from './directives/drag';
export type * from './directives/observe';
export type * from './directives/prop';
export type * from './directives/px';
export type * from './directives/resize';
export type * from './directives/ripple';
export type * from './directives/scroll';
export type * from './directives/spy';
export type * from './directives/upload';
export type * from './components/icon';
export type * from './components/badge';
export type * from './components/button';
export type * from './components/triangle';
export type * from './components/layer';
export type * from './components/label';
export type * from './components/input';
export type * from './components/loading';
export type * from './components/loading-bar';
export type * from './components/msgbox';
export type * from './components/divider';
export type * from './components/cell';
export type * from './components/cell-group';
export type * from './components/checkbox';
export type * from './components/radio';
export type * from './components/sign';
export type * from './components/roll';
export type * from './components/row';
export type * from './components/col';
export type * from './components/autocomplete';
export type * from './components/overlay';
export type * from './components/popup';
export type * from './components/dropdown';
export type * from './components/tooltip';
export type * from './components/transition-slide';
export type * from './components/switch';
export type * from './components/navbar';
export type * from './components/notify';
export type * from './components/actionsheet';
export type * from './components/calendar';
export type * from './components/circle-progress';
export type * from './components/collapse';
export type * from './components/collapse-item';
export type * from './components/date-chooser';
export type * from './components/date-native-picker';
export type * from './components/picker';
export type * from './components/progress';
export type * from './components/slider';
export type * from './components/date-picker';
export type * from './components/field';
export type * from './components/form';
export type * from './components/form-el';
export type * from './components/image';
export type * from './components/color-picker';
export type * from './components/list';
export type * from './components/modal';
export type * from './components/page';
export type * from './components/search';
export type * from './components/select';
export type * from './components/skeleton';
export type * from './components/steps';
export type * from './components/step';
export type * from './components/stepper';
export type * from './components/number-keyboard';
export type * from './components/toast';
export type * from './components/pull-refresh';
export type * from './components/dialog';
export type * from './components/swipe-cell';
export type * from './components/tabbar';
export type * from './components/table';
export type * from './components/tabs';
export type * from './components/tab';
export type * from './components/carousel';
export type * from './components/carousel-item';
export type * from './components/rich-image';
export type * from './components/image-preview';
declare const install: (app: App) => void;
declare const version = "2.0.10";
export { isDark, useDark } from './utils';
export { install as default, install, version };
