import { FunctionPlugin } from 'vue';

/***** 按需导出 *****/
export * from './directives/anchor';
export * from './directives/drag';
export * from './directives/observe';
export * from './directives/prop';
export * from './directives/px';
export * from './directives/resize';
export * from './directives/ripple';
export * from './directives/scroll';
export * from './directives/spy';
export * from './directives/upload';
export * from './components/icon';
export * from './components/badge';
export * from './components/button';
export * from './components/triangle';
export * from './components/layer';
export * from './components/label';
export * from './components/input';
export * from './components/loading';
export * from './components/loading-bar';
export * from './components/msgbox';
export * from './components/divider';
export * from './components/cell';
export * from './components/cell-group';
export * from './components/checkbox';
export * from './components/radio';
export * from './components/sign';
export * from './components/roll';
export * from './components/row';
export * from './components/col';
export * from './components/autocomplete';
export * from './components/overlay';
export * from './components/popup';
export * from './components/dropdown';
export * from './components/tooltip';
export * from './components/transition-slide';
export * from './components/switch';
export * from './components/navbar';
export * from './components/notify';
export * from './components/actionsheet';
export * from './components/calendar';
export * from './components/circle-progress';
export * from './components/collapse';
export * from './components/collapse-item';
export * from './components/date-chooser';
export * from './components/date-native-picker';
export * from './components/picker';
export * from './components/progress';
export * from './components/slider';
export * from './components/date-picker';
export * from './components/field';
export * from './components/form';
export * from './components/form-el';
export * from './components/image';
export * from './components/color-picker';
export * from './components/list';
export * from './components/modal';
export * from './components/page';
export * from './components/search';
export * from './components/select';
export * from './components/skeleton';
export * from './components/steps';
export * from './components/step';
export * from './components/stepper';
export * from './components/number-keyboard';
export * from './components/toast';
export * from './components/pull-refresh';
export * from './components/dialog';
export * from './components/swipe-cell';
export * from './components/tabbar';
export * from './components/table';
export * from './components/tabs';
export * from './components/tab';
export * from './components/carousel';
export * from './components/carousel-item';
export * from './components/rich-image';
export * from './components/image-preview';
export type * from './components/actionsheet/props';
export type * from './components/autocomplete/props';
export type * from './components/badge/props';
export type * from './components/button/props';
export type * from './components/calendar/props';
export type * from './components/carousel/props';
export type * from './components/cell/props';
export type * from './components/cell-group/props';
export type * from './components/checkbox/props';
export type * from './components/circle-progress/props';
export type * from './components/col/props';
export type * from './components/collapse/props';
export type * from './components/collapse-item/props';
export type * from './components/color-picker/props';
export type * from './components/date-chooser/props';
export type * from './components/date-native-picker/props';
export type * from './components/date-picker/props';
export type * from './components/dialog/props';
export type * from './components/divider/props';
export type * from './components/dropdown/props';
export type * from './components/field/props';
export type * from './components/form/props';
export type * from './components/form-el/props';
export type * from './components/icon/props';
export type * from './components/image/props';
export type * from './components/image-preview/props';
export type * from './components/input/prop';
export type * from './components/label/props';
export type * from './components/layer/props';
export type * from './components/list/props';
export type * from './components/loading/props';
export type * from './components/loading-bar/props';
export type * from './components/modal/props';
export type * from './components/msgbox/props';
export type * from './components/navbar/props';
export type * from './components/notify/props';
export type * from './components/number-keyboard/props';
export type * from './components/overlay/props';
export type * from './components/page/props';
export type * from './components/picker/props';
export type * from './components/popup/props';
export type * from './components/progress/props';
export type * from './components/pull-refresh/props';
export type * from './components/radio/props';
export type * from './components/rich-image/props';
export type * from './components/roll/props';
export type * from './components/row/props';
export type * from './components/search/props';
export type * from './components/select/props';
export type * from './components/sign/props';
export type * from './components/skeleton/props';
export type * from './components/slider/props';
export type * from './components/stepper/props';
export type * from './components/steps/props';
export type * from './components/swipe-cell/props';
export type * from './components/switch/props';
export type * from './components/tab/props';
export type * from './components/tabbar/props';
export type * from './components/table/props';
export type * from './components/tabs/props';
export type * from './components/toast/props';
export type * from './components/tooltip/props';
export type * from './components/transition-slide/props';
export type * from './components/triangle/props';
export type * from './directives/anchor/anchor';
export type * from './directives/drag/drag';
export type * from './directives/observe/observe';
export type * from './directives/px/px';
export type * from './directives/resize/resize';
export type * from './directives/ripple/ripple';
export type * from './directives/scroll/scroll';
export type * from './directives/spy/spy';
export type * from './directives/upload/upload';
declare const install: FunctionPlugin;
declare const version = "1.9.20";
export { install as default, install, version };
